SudamericanGreen/Controllers/Personas/TipoPersonaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entities;
using Evaluaciones_Tecnicas.Filter;
using Negocio;

namespace Evaluaciones_Tecnicas.Controllers.Personas
{
    public class TipoPersonaController : Controller
    {
        //
        // GET: /TipoPersona/
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Index()
        {
            TipoPersonaComponent tipoPersonaComponent = new TipoPersonaComponent();
            return View(tipoPersonaComponent.Read());
        }

        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult ErrorPage(int id)
        {

            TipoPersonaComponent tipoPersonaComponent = new TipoPersonaComponent();
            return View(tipoPersonaComponent.ReadBy(id));
        }
        [AuthorizerUser(_roles: "Administrador")]
        //
        // GET: /TipoPersona/Create
        public ActionResult Create()
        {
            return View();
        }
        [AuthorizerUser(_roles: "Administrador")]

        //
        // POST: /TipoPersona/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                TipoPersonaComponent tipoPersonaComponent = new TipoPersonaComponent();
                TipoPersona tipoPersona = new TipoPersona();
                tipoPersona.tipoPersona = collection.Get("tipoPersona");
                if (tipoPersonaComponent.Create(tipoPersona)is null)
                {
                    tipoPersona = tipoPersonaComponent.ReadBy(tipoPersona.tipoPersona);
                    return RedirectToAction("ErrorPage", new { id = tipoPersona.Id });
                }
                else
                {
                    return RedirectToAction("Index");
                }

               
            }
            catch (Exception e)
            {
                return View();
            }
        }
        [AuthorizerUser(_roles: "Administrador")]
        //
        // GET: /TipoPersona/Edit/5
        public ActionResult Edit(int id)
        {

            TipoPersonaComponent tipoPersonaComponent = new TipoPersonaComponent();
            return View(tipoPersonaComponent.ReadBy(id));
        }
        [AuthorizerUser(_roles: "Administrador")]
        //
        // POST: /TipoPersona/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                TipoPersonaComponent tipoPersonaComponent = new TipoPersonaComponent();
                TipoPersona tipoPersona = new TipoPersona();
                tipoPersona.tipoPersona = collection.Get("tipoPersona");
                tipoPersona.Id = id;
                if (tipoPersonaComponent.Update(tipoPersona))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    tipoPersona = tipoPersonaComponent.ReadBy(tipoPersona.tipoPersona);
                    return RedirectToAction("ErrorPage", new { id });
                   
                }
            }
            catch
            {
                return View();
            }
        }
        [AuthorizerUser(_roles: "Administrador")]
        //
        // GET: /TipoPersona/Delete/5
        public ActionResult Delete(int id)
        {
            TipoPersonaComponent tipoPersonaComponent = new TipoPersonaComponent();
            return View(tipoPersonaComponent.ReadBy(id));
        }
        [AuthorizerUser(_roles: "Administrador")]
        //
        // POST: /TipoPersona/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                TipoPersonaComponent tipoPersonaComponent = new TipoPersonaComponent();
                tipoPersonaComponent.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SudamericanGreen/Views/TipoPersona/Create.cshtml
@model Entities.TipoPersona

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<link href="~/Content/modern-business.css" rel="stylesheet" />

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
       <div class="d-flex flex-column" style="max-width:60%">
        <div class="container-fluid">
            <div class="card shadow mb-4">
                <div class=" card-header py-3" >
                    <h6 class="m-0 font-weight-bold text-primary">Crear un Tipo de Persona </h6>



                </div>
                   <div class="card-body">
             @Html.ValidationSummary(true, "", new { @class = "text-danger" })

      <h5  class="text-justify">  
            @Html.LabelFor(model => model.tipoPersona, new { @class = "control-label col-md-2" })
</h5>
          
                @Html.EditorFor(model => model.tipoPersona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tipoPersona, "", new { @class = "text-danger" })
            
        </div>

       <input type="button" class="btn btn-outline-primary " style="margin-left:30%;max-width:40%"   value="Volver" onclick="location.href='@Url.Action("Index", "tipoPersona")'" />

                <br />

                 <input type="submit" style="margin-left:30%;max-width:40%" value="Crear" class="btn btn-outline-info" />
  
         </div>
     </div>

    </div>
}

SudamericanGreen/Views/TipoPersona/Delete.cshtml
@model Entities.TipoPersona

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}




<link href="~/Content/modern-business.css" rel="stylesheet" />

<div>
    <h3>¿Esta seguro de eliminar el "" <i>"@Html.DisplayFor(model => model.tipoPersona)"</i>?</h3>
    <hr />


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Eliminar" style="margin-left:1%" class="btn btn-outline-info" />
   
    <br />
    <input type="button" class="btn btn-outline-primary " style="float:left;margin-left:1%;margin-top:3%" value="Volver" onclick="location.href='@Url.Action("Index", "tipoPersona")'" />
</div>
    }
</div>

SudamericanGreen/Views/TipoPersona/Edit.cshtml
@model Entities.TipoPersona

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<link href="~/Content/modern-business.css" rel="stylesheet" />

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
       <div class="d-flex flex-column" style="max-width:60%">
        <div class="container-fluid">
            <div class="card shadow mb-4">
                <div class=" card-header py-3" >
                    <h6 class="m-0 font-weight-bold text-primary">Actualizar el  <i>"@Html.DisplayFor(model => model.tipoPersona)"</i></h6>



                </div>
                   <div class="card-body">
             @Html.ValidationSummary(true, "", new { @class = "text-danger" })

      <h5  class="text-justify">  
            @Html.LabelFor(model => model.tipoPersona, new { @class = "control-label col-md-2" })
</h5>
          
                @Html.EditorFor(model => model.tipoPersona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tipoPersona, "", new { @class = "text-danger" })
            
        </div>

       <input type="button" class="btn btn-outline-primary " style="margin-left:30%;max-width:40%"   value="Volver" onclick="location.href='@Url.Action("Index", "tipoPersona")'" />

                <br />

                 <input type="submit" style="margin-left:30%;max-width:40%" value="Actualizar" class="btn btn-outline-info" />
  
         </div>
     </div>

    </div>
}

SudamericanGreen/Views/TipoPersona/ErrorPage.cshtml
@model Entities.TipoPersona

@{
    ViewBag.Title = "ErrorPage";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}



<link href="~/Content/modern-business.css" rel="stylesheet" />



<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">



        <!-- Begin Page Content -->
        <div class="container-fluid">

            <!-- 404 Error Text -->
            <div class="text-center">
                <div class="error mx-auto" data-text="Error">Error</div>
                <p class="lead text-gray-800 mb-5">No se puede agregrar o modificar el Tipo de Persona <i>"@Html.DisplayFor(model => model.tipoPersona) "</i>.Ya existe
<p class="text-gray-500 mb-0">Por favor colocar otro nombre</p>
                <a href="@Url.Action("Index", "tipoPersona")">← volver al inicio</a>
            </div>

        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->

SudamericanGreen/Views/TipoPersona/Index.cshtml
@model IEnumerable<Entities.TipoPersona>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}



<div id="content-wrapper" class="d-flex flex-column">
  <!-- Main Content -->
    <div id="content">

      <!-- Begin Page Content -->
        <div class="container-fluid">
         <div class="card shadow mb-4">
              <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Lista de Tipo de Persona </h6>
              </div>
              <div class="card-body"> 
                 <div class="table-responsive">
                   <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                         <div class="col-sm-12">
                <table  class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;" >   
                  <thead>

                <tr  role="row">
                    <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 103px;">@Html.DisplayNameFor(model => model.tipoPersona) </th>

       
         <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 162px;">Acciones</th>
    </tr>
     </thead>
       <tbody>
@foreach (var item in Model) {
    <tr role="row" class="odd">
        <td class="sorting_1">
            @Html.DisplayFor(modelItem => item.tipoPersona)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
           
            @Html.ActionLink("Eliminar", "Delete", new { id=item.Id })
        </td>
    </tr>
}
</tbody>
</table>

              </div>
                </div>
             </div>
               <input type="button" class="btn btn-outline-primary " style="float:right" value="Crear" onclick="location.href='@Url.Action("create", "TipoPersona")'" />
          
         </div>
        </div>
       </div>
      </div>
     </div>