SudamericanGreen/Controllers/Servicios/UsuarioRolesController.cs
using Evaluaciones.Models;
using Entities;
using Negocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Evaluaciones_Tecnicas.Filter;

namespace Evaluaciones.Controllers
{
    //[Authorize(Roles = "Administrador")]//para entrar en admin debe estar logueado y  asignarle el rol
    public class UsuarioRolesController : Controller
    {
        // GET: UsuarioRoles
        [AuthorizerUser(_roles: "Administrador,RRHH")]
        public ActionResult Index(int id)
        {
            UsuarioRolesComponent usuarioRolesComponent = new UsuarioRolesComponent();
            List<UsuarioRoles> usuarioRoles = new List<UsuarioRoles>();
            usuarioRoles = usuarioRolesComponent.ReadByUsuario(id);
            if (usuarioRoles.Count==0)
            {
                UsuarioRoles usuario = new UsuarioRoles();
                usuario.usuarios.Id = id;
                usuarioRoles.Add(usuario);
                    
            }

            return View(usuarioRoles);
        }

        // GET: UsuarioRoles/Details/5
        [AuthorizerUser(_roles: "Administrador,RRHH")]
        public ActionResult Details(int id,string idRol)
        {
            UsuarioRolesComponent usuarioRolesComponent = new UsuarioRolesComponent();
            return View(usuarioRolesComponent.ReadBy(idRol,id));
        }

        [AuthorizerUser(_roles: "Administrador,RRHH")]
        public ActionResult Usuario (int Id)
        {
            UsuarioRolesComponent usuarioRolesComponent = new UsuarioRolesComponent();
            return View(usuarioRolesComponent.ReadByUsuario(Id));
        }
        [AuthorizerUser(_roles: "Administrador,RRHH")]
        public ActionResult Roles(String Id)
        {
            UsuarioRolesComponent usuarioRolesComponent = new UsuarioRolesComponent();
            return View(usuarioRolesComponent.ReadByRoles(Id));
        }

        // GET: UsuarioRoles/Create
        [AuthorizerUser(_roles: "Administrador,RRHH")]
        public ActionResult Create(int id)
        {
            UsuarioRolesModels usuarioRoles = new UsuarioRolesModels();
            List<UsuarioRolesModels> result = new List<UsuarioRolesModels>();
            result = usuarioRoles.obtenerRolesDisponiblesDelUsuario(id);
            result.Select(y =>
                            new
                            {
                                id_Rol = y.id_Rol,
                                name = y.name
                            });

            ViewBag.RolesLista = new SelectList(result, "id_Rol", "name");




            return View(usuarioRoles.ReadyBy(id));
        }

        // POST: UsuarioRoles/Create
        [AuthorizerUser(_roles: "Administrador,RRHH")]
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                UsuarioRolesComponent usuarioRolesComponent = new UsuarioRolesComponent();
                UsuarioRoles usuarioRoles = new UsuarioRoles();
                usuarioRoles.roles.id = collection.Get("id_Rol");
                usuarioRoles.usuarios.Id =int.Parse( collection.Get("id_Usuario"));
                usuarioRolesComponent.Create(usuarioRoles);
                // TODO: Add insert logic here

                return RedirectToAction("Index",new { id = usuarioRoles.usuarios.Id });
            }
            catch (Exception e)
            {
                return View();
            }
        }

        // GET: UsuarioRoles/Edit/5
        [AuthorizerUser(_roles: "Administrador,RRHH")]
        public ActionResult Edit(int id_Usuario, String id_Roles)
        {
            try
            {
                UsuarioRolesModels usuarioRoles = new UsuarioRolesModels();
                List<UsuarioRolesModels> result = new List<UsuarioRolesModels>();
                result = usuarioRoles.obtenerRolesDisponiblesDelUsuario(id_Usuario);
                result.Select(y =>
                                new
                                {
                                    id_Rol = y.id_Rol,
                                    name = y.name
                                });

                ViewBag.RolesLista = new SelectList(result, "id_Rol", "name");
                    

                return View(usuarioRoles.ReadBy(id_Roles, id_Usuario));
            }
            catch (Exception e)
            {

                throw;
            }
          
        }

        // POST: UsuarioRoles/Edit/5
        [AuthorizerUser(_roles: "Administrador,RRHH")]
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                UsuarioRolesComponent usuarioRolesComponent = new UsuarioRolesComponent();
                UsuarioRoles usuario = new UsuarioRoles();
                usuario.roles.id = collection.Get("id_Rol");
                usuario.usuarios.Id =int.Parse( collection.Get("id_Usuario"));
                usuarioRolesComponent.Update(usuario);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: UsuarioRoles/Delete/5
        [AuthorizerUser(_roles: "Administrador,RRHH")]
        public ActionResult Delete(string id_Usuario, String id_Roles)
        {
            return View();
        }

        // POST: UsuarioRoles/Delete/5
        [AuthorizerUser(_roles: "Administrador,RRHH")]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SudamericanGreen/Controllers/Usuario/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Evaluaciones.Models;
using System.Threading.Tasks;
using Negocio;
using Entities;
using System.Web.UI.WebControls;
using Negocio.Servicios;
using Evaluaciones_Tecnicas.Filter;

namespace Evaluaciones.Controllers
{
    //[Authorize(Roles = "Administrador")]//para entrar en admin debe estar logueado y  asignarle el rol
    public class UsuarioController : Controller
    {
        [AuthorizerUser(_roles: "Administrador")]
        // GET: Usuario
        public ActionResult Index()
        {
            UsuariosComponent usuariosComponent = new UsuariosComponent();
           
            return View(usuariosComponent.Read());
        }

        // GET: Usuario/Details/5
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Details(int id)
        {
            return View();
        }
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Create()
        {


            return View();
        }
        // Post: Usuario/Create
        [AuthorizerUser(_roles: "Administrador")]
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                Usuarios usuario = new Usuarios();
                usuario.Password = collection.Get("Password");
                usuario.Email = collection.Get("Email");
                usuario.UserName = collection.Get("Email");
                usuario.Nombre= collection.Get("Nombre");
                usuario.Apellido = collection.Get("Apellido");
                UsuariosComponent usuariosComponent = new UsuariosComponent();
                
              bool result = usuariosComponent.Crear(usuario);

                if (result)
                {
                    return RedirectToAction("index");
                }
                else
                {
                    RedirectToAction("ErrorPage");
                }
            }
            catch (Exception e)
            {
                return RedirectToAction("index");
                throw;
            }

            return RedirectToAction("index");

        }

        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult UsuarioExamen()
        {

            return View();
        }

        [HttpPost]
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult UsuarioExamen(FormCollection collection)
        {
            return View();

        }

        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult ErrorPage(String Username)
        {
            Usuarios usuarios = new Usuarios();
            usuarios.UserName = Username;
            return View(usuarios);
        }

        // GET: Usuario/Edit/5
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Usuario/Edit/5
        [AuthorizerUser(_roles: "Administrador")]
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Usuario/Delete/5
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Delete(int id)
        {
            UsuariosComponent usuariosComponent = new UsuariosComponent();
            return View(usuariosComponent.ReadBy(id));
        }

        // POST: Usuario/Delete/5
        [HttpPost]
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                UsuariosComponent usuariosComponent = new UsuariosComponent();
                Usuarios usuarios = new Usuarios();
                usuarios.Id = id;
                usuariosComponent.Delete(id);
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SudamericanGreen/Views/Usuario/Create.cshtml
@model Entities.Usuarios

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<link href="~/Content/modern-business.css" rel="stylesheet" />





@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="d-flex flex-column">
        <div class="container-fluid">
            <div class="card shadow mb-4" style="min-width:550px">
                <div class=" card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Crear un usuario del sistema</h6>



                </div>
                <div class="card-body">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })



                    <h5 class="text-justify">Nombre</h5>
                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                    <br />
                    <h5 class="text-justify">Apellido</h5>
                    @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })

                    <br />
                    <h5 class="text-justify">Email</h5>
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })

                    <br />
                    <h5 class="text-justify">Contraseña</h5>

                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>


                <input type="button" class="btn btn-outline-primary " style="float:right" value="Volver" onclick="location.href='@Url.Action("Index", "Usuario")'" />

                <br />

                <input type="submit" value="Crear" class="btn btn-outline-info" />

            </div>
        </div>
    </div>
}

SudamericanGreen/Views/Usuario/Delete.cshtml
@model Entities.Usuarios

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<link href="~/Content/modern-business.css" rel="stylesheet" />

<div>
    <h3>¿Esta seguro de eliminar <i> "@Html.DisplayFor(model => model.Email)"</i>?</h3>
    <hr />


   

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Eliminar" class="btn btn-outline-info" />
    <input type="button" class="btn btn-outline-primary " style="float:right" value="Volver" onclick="location.href='@Url.Action("Index", "Usuario")'" />
</div>
    }
</div>

SudamericanGreen/Views/Usuario/ErrorPage.cshtml
@model Entities.Usuarios

@{
    ViewBag.Title = "ErrorPage";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<link href="~/Content/modern-business.css" rel="stylesheet" />



<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">



        <!-- Begin Page Content -->
        <div class="container-fluid">

            <!-- 404 Error Text -->
            <div class="text-center">
                <div class="error mx-auto" data-text="Error">Error</div>
                <p class="lead text-gray-800 mb-5">No se puede agregrar o modificar el Usuario <i>"@Html.DisplayFor(model => model.UserName) "</i>.Ya existe
<p class="text-gray-500 mb-0">Por favor colocar otro nombre</p>
                <a href="@Url.Action("Index", "usuario")">← volver al inicio</a>
            </div>

        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->


</div>

SudamericanGreen/Views/Usuario/Index.cshtml
@model IEnumerable<Entities.Usuarios>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<link href="~/Content/modern-business.css" rel="stylesheet" />




<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">


        <!-- Begin Page Content -->
        <div class="container-fluid">


            <!-- DataTales Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Lista de usuarios de sistema</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">

                            <div class="col-sm-12">
                                <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 103px;">Email</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 103px;">Nombre</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 103px;">Apellido</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 103px;">Bloqueado</th>


                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 162px;">Acciones</th>
                                        </tr>
                                    </thead>

                                    <tbody>

                                        @foreach (var item in Model)
                                        {
                                        <tr role="row" class="odd">
                                            <td class="sorting_1">
                                                @Html.DisplayFor(modelItem => item.Email)
                                            </td>

                                            <td class="sorting_1">
                                                @Html.DisplayFor(modelItem => item.Nombre)
                                            </td>
                                            <td class="sorting_1">
                                                @Html.DisplayFor(modelItem => item.Apellido)
                                            </td>
                                            <td class="sorting_1">
                                                @Html.DisplayFor(modelItem => item.Bloqueado)
                                            </td>
                                         

                                            <td>
                                                @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |

                                                @Html.ActionLink("Eliminar", "Delete", new { id = item.Id }) |
                                                @Html.ActionLink("Desbloquear", "Desbloquear", new { id = item.Id })|
                                                @Html.ActionLink("Ver permisos", "index", "UsuarioRoles", new { id = item.Id }, null)
                                            </td>


                                        </tr>
                                        }



                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <input type="button" class="btn btn-outline-primary " style="float:right" value="Crear" onclick="location.href='@Url.Action("create", "Usuario")'" />
                </div>
            </div>

        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->


</div>