SudamericanGreen/Controllers/Servicios/Permisos/PermisoController.cs
using Entities;
using Evaluaciones_Tecnicas.Filter;
using Negocio.Servicios.Permisos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Evaluaciones_Tecnicas.Controllers
{
    public class PermisoController : Controller
    {
        [AuthorizerUser(_roles: "Administrador")]
        // GET: /Permiso/
        public ActionResult Index()
        {
            PermisoComponent permisoComponent = new PermisoComponent();
         

            return View(permisoComponent.Read());
        }

        [AuthorizerUser(_roles: "Administrador")]
        // GET: /Permiso/Details/5
        public ActionResult ErroPage(String id)
        {
            PermisoComponent permisoComponent = new PermisoComponent();
            return View(permisoComponent.ReadBy(id));
        }

        [AuthorizerUser(_roles: "Administrador")]
        // GET: /Permiso/Create
        public ActionResult Create()
        {
            return View();
        }

        [AuthorizerUser(_roles: "Administrador")]
        // POST: /Permiso/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                Permiso permiso = new Permiso();
                permiso.name = collection.Get("name");
                PermisoComponent permisoComponent = new PermisoComponent();
                if (permisoComponent.Create(permiso) is null)
                {
                    return RedirectToAction("ErroPage", new { id = permiso.name});
                }
                else
                {
                    return RedirectToAction("Index");
                }
                // TODO: Add insert logic here

                
            }
            catch (Exception e)
            {
                return View();
            }
        }

        [AuthorizerUser(_roles: "Administrador")]
        // GET: /Permiso/Edit/5
        public ActionResult Edit(int id)
        {
            PermisoComponent permisoComponent = new PermisoComponent();
            return View(permisoComponent.ReadBy(id));
        }
        [AuthorizerUser(_roles: "Administrador")]
        //
        // POST: /Permiso/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                Permiso permiso = new Permiso();
                permiso.name = collection.Get("name");
                permiso.Id = id;
                PermisoComponent permisoComponent = new PermisoComponent();
                if (permisoComponent.Verificar(permiso))
                {
                    permisoComponent.Update(permiso);
                    return RedirectToAction("Index");

                }
                else
                {
                    return RedirectToAction("ErroPage", new { id = permiso.name });
                }
               
            }
            catch (Exception e)
            {
                return View();
            }
        }
        [AuthorizerUser(_roles: "Administrador")]
        //
        // GET: /Permiso/Delete/5
        public ActionResult Delete(int id)
        {
            PermisoComponent permisoComponent = new PermisoComponent();
            return View(permisoComponent.ReadBy(id));
        }
        [AuthorizerUser(_roles: "Administrador")]
        //
        // POST: /Permiso/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                PermisoComponent permisoComponent = new PermisoComponent();
                permisoComponent.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SudamericanGreen/Controllers/Servicios/Permisos/RolesController.cs
using Entities;
using Evaluaciones_Tecnicas.Filter;
using Negocio;
using Negocio.Servicios.Permisos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Evaluaciones.Controllers
{
    public class RolesController : Controller
    {
        // GET: Roles
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Index()
        {
            RolesComponent roles = new RolesComponent();
         
            return View(roles.Read());
        }

        // GET: Roles/Details/5
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Details(int id)
        {
            RolesComponent roles = new RolesComponent();
            return View(roles.ReadBy(id));
        }

        // GET: Roles/Create
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        [AuthorizerUser(_roles: "Administrador")]
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                RolesComponent rolesComponent = new RolesComponent();
                Roles roles = new Roles();
                roles.name = collection.Get("name");
                if (rolesComponent.Create(roles) is null)
                {
                   
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("ErrorPage",new { id=roles.name});
                }
            }
            catch (Exception e)
            {
                return View();
            }
        }
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult VerPermisos(int id)
        {
            RolesComponent roles = new RolesComponent();
            Roles roles1 = new Roles();
      
           roles1= roles.ReadBy(id);
            roles.ObtenerComposite(roles1);
            return View(roles1);
        }

        // GET: Roles/Edit/5
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Edit(int id)
        {
            RolesComponent rolesComponent = new RolesComponent();
            return View(rolesComponent.ReadBy(id));
        }

        // POST: Roles/Edit/5
        [AuthorizerUser(_roles: "Administrador")]
        [HttpPost]
        public ActionResult Edit(string id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                RolesComponent rolesComponent = new RolesComponent();
                Roles roles = new Roles();
                roles.name = collection.Get("name");
                roles.id = id;
                Roles rolBase = new Roles();
                if (rolesComponent.Verificar(roles))
                {
                    rolesComponent.Update(roles);
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("ErrorPage",new { id=roles.name});
                }


            
            }
            catch (Exception e)
            {
                return View();
            }
        }

        // GET: Roles/Delete/5
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Delete(int id)
        {

            RolesComponent rolesComponent = new RolesComponent();
            return View(rolesComponent.ReadBy(id));
        }

        // POST: Roles/Delete/5
        //[AuthorizerUser(_roles: "Administrador")]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                RolesComponent rolesComponent = new RolesComponent();
                rolesComponent.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [AuthorizerUser(_roles: "Administrador")]

        public ActionResult ErrorPage(String id)
        {
            RolesComponent roles = new RolesComponent();
            return View(roles.ReadBy(id));
        }
        #region ABM COmposite
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Agregar(int id)
        {
            RolesComponent rolesComponent = new RolesComponent();

            Roles roles = new Roles();
            roles = rolesComponent.RolesDiponibles(id);

            roles.listaRol.Select(y =>
                                new
                                {
                                    y.Id,
                                    y.name
                                });

            ViewBag.ListaSedes = new SelectList(roles.listaRol, "Id", "name");

                
                
                
            return View(roles);
        }

        // POST: Roles/Create
        [AuthorizerUser(_roles: "Administrador")]
        [HttpPost]
        public ActionResult Agregar(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                RolesComponent rolesComponent = new RolesComponent();
                Roles roles = new Roles();
                Roles roles1 = new Roles();

                roles1.Id =int.Parse( collection.Get("name"));
                roles.Id = int.Parse(collection.Get("id"));
                roles.permiso = roles1;
                rolesComponent.CreateComposite(roles);
                return RedirectToAction("VerPermisos", new { id = int.Parse(collection.Get("id")) });

            }
            catch (Exception e)
            {
                return View();
            }
        }
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult DeleteComposite(int id)
        {

            RolesComponent rolesComponent = new RolesComponent();

            Roles roles = new Roles();
            roles = rolesComponent.ReadBy(id);
            roles.listaRol = rolesComponent.ObtenerPermisosORolesDeUnRol(id);

            roles.listaRol.Select(y =>
                                new
                                {
                                    y.Id,
                                    y.name
                                });

            ViewBag.ListaSedes = new SelectList(roles.listaRol, "Id", "name");
            return View(roles);
        }

        // POST: Roles/Delete/5
        [AuthorizerUser(_roles: "Administrador")]
        [HttpPost]
        public ActionResult DeleteComposite(FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                RolesComponent rolesComponent = new RolesComponent();
                Roles roles = new Roles();
                Roles roles1 = new Roles();
                roles1.Id = int.Parse(collection.Get("name"));
                roles.Id = int.Parse(collection.Get("id"));
                roles.permiso = roles1;
                rolesComponent.DeleteComposite(roles);
                return RedirectToAction("VerPermisos", new { id = int.Parse(collection.Get("id")) });
            }
            catch (Exception e)
            {
                return View();
            }
        }
        #endregion

    }
}

SudamericanGreen/Views/Permiso/Create.cshtml
@model Entities.Permiso

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<link href="~/Content/modern-business.css" rel="stylesheet" />

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
       <div class="d-flex flex-column" style="max-width:60%">
        <div class="container-fluid">
            <div class="card shadow mb-4">
                <div class=" card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Crear un Permiso</h6>



                </div>
                   <div class="card-body">
             @Html.ValidationSummary(true, "", new { @class = "text-danger" })

      <h5  >  
            @Html.LabelFor(model => model.name, new { @class = "control-label col-md-2" })
</h5>
          
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            
        </div>

      <input type="button" class="btn btn-outline-primary " style="margin-left:30%;max-width:40%"   value="Volver" onclick="location.href='@Url.Action("Index", "Permiso")'" />

                <br />

                <input type="submit" style="margin-left:30%;max-width:40%" value="Crear" class="btn btn-outline-info" />
  
         </div>
     </div>

    </div>
}

SudamericanGreen/Views/Permiso/Delete.cshtml
@model Entities.Permiso

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}




<link href="~/Content/modern-business.css" rel="stylesheet" />

<div>
    <h3>¿Esta seguro de eliminar el Permiso <i>"@Html.DisplayFor(model => model.name)"</i>?</h3>
    <hr />


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Eliminar" style="margin-left:1%" class="btn btn-outline-info" />
    <br />
    <input type="button" class="btn btn-outline-primary " style="float:left;margin-left:1%;margin-top:2%" value="Volver" onclick="location.href='@Url.Action("Index", "Permiso")'" />
</div>
    }
</div>

SudamericanGreen/Views/Permiso/Edit.cshtml
@model Entities.Permiso

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<link href="~/Content/modern-business.css" rel="stylesheet" />

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
       <div class="d-flex flex-column" style="max-width:60%">
        <div class="container-fluid">
            <div class="card shadow mb-4">
                <div class=" card-header py-3" >
                    <h6 class="m-0 font-weight-bold text-primary">Actualizar el  Permiso<i>"@Html.DisplayFor(model => model.name)"</i></h6>



                </div>
                   <div class="card-body">
             @Html.ValidationSummary(true, "", new { @class = "text-danger" })

      <h5  class="text-justify">  
            @Html.LabelFor(model => model.name, new { @class = "control-label col-md-2" })
</h5>
          
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            
        </div>

       <input type="button" class="btn btn-outline-primary " style="margin-left:30%;max-width:40%"   value="Volver" onclick="location.href='@Url.Action("Index", "Permiso")'" />

                <br />

                 <input type="submit" style="margin-left:30%;max-width:40%" value="Guardar" class="btn btn-outline-info" />
  
         </div>
     </div>

    </div>
}

SudamericanGreen/Views/Permiso/ErroPage.cshtml
@model Entities.Permiso

@{
    ViewBag.Title = "ErroPage";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}



<link href="~/Content/modern-business.css" rel="stylesheet" />



<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">



        <!-- Begin Page Content -->
        <div class="container-fluid">

            <!-- 404 Error Text -->
            <div class="text-center">
                <div class="error mx-auto" data-text="Error">Error</div>
                <p class="lead text-gray-800 mb-5">No se puede agregrar o modificar el Permiso <i>"@Html.DisplayFor(model => model.name) "</i>.Ya existe
<p class="text-gray-500 mb-0">Por favor colocar otro nombre</p>
                <a href="@Url.Action("Index", "Permiso")">← volver al inicio</a>
            </div>

        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->

SudamericanGreen/Views/Permiso/Index.cshtml
@model IEnumerable<Entities.Permiso>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}



<div id="content-wrapper" class="d-flex flex-column">
  <!-- Main Content -->
    <div id="content">

      <!-- Begin Page Content -->
        <div class="container-fluid">
         <div class="card shadow mb-4">
              <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Lista de Permisos </h6>
              </div>
              <div class="card-body"> 
                 <div class="table-responsive">
                   <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                         <div class="col-sm-12">
                <table  class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;" >   
                  <thead>

                <tr  role="row">
                    <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 103px;"> @Html.DisplayNameFor(model => model.name)</th>

       
         <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 162px;">Acciones</th>
    </tr>
     </thead>
       <tbody>
@foreach (var item in Model) {
    <tr role="row" class="odd">
        <td class="sorting_1">
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
         
            @Html.ActionLink("Eliminar", "Delete", new { id=item.Id })
        </td>
    </tr>
}
</tbody>
</table>

              </div>
                </div>
             </div>
               <input type="button" class="btn btn-outline-primary " style="float:right" value="Crear" onclick="location.href='@Url.Action("create", "Permiso")'" />
          
         </div>
        </div>
       </div>
      </div>
     </div>