SudamericanGreen/Controllers/Personas/DireccionPersonaController.cs
using Evaluaciones_Tecnicas.Filter;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Negocio;
using Entities;
namespace Evaluaciones_Tecnicas.Controllers.Personas
{
    public class DireccionPersonaController : Controller
    {
        [AuthorizerUser(_roles: "Administrador")]
        //
        // GET: /DireccionPersona/
        public ActionResult Index(int id)
        {
            DireccionPersona persona = new DireccionPersona();
            DireccionPersonaComponent direccionPersona = new DireccionPersonaComponent();
            PersonaComponent personaComponent = new PersonaComponent();
            persona.direccionPersona = direccionPersona.ReadByPersona(id);
            persona.persona = personaComponent.ReadBy(id);
            return View(persona);
        }
        [AuthorizerUser(_roles: "Administrador")]
        //
        // GET: /DireccionPersona/Details/5
        public ActionResult ErroPage(int id)
        {
            DireccionPersona persona = new DireccionPersona();
           
            persona.persona.Id = id;
            


            return View(persona);
        }
        [AuthorizerUser(_roles: "Administrador")]
        //
        // GET: /DireccionPersona/Create
        public ActionResult Create(int id)
        {
            DireccionPersona persona = new DireccionPersona();
            PersonaComponent personaComponent = new PersonaComponent();
            persona.persona = personaComponent.ReadBy(id);

            return View(persona);
        }
        [AuthorizerUser(_roles: "Administrador")]
        //
        // POST: /DireccionPersona/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {

                // TODO: Add insert logic here
                DireccionPersona persona = new DireccionPersona();
                DireccionPersonaComponent direccionPersonaComponent = new DireccionPersonaComponent();
                persona.persona.Id = int.Parse(collection.Get("persona.Id"));
                persona.direccion.direccion = collection.Get("direccion.direccion");
                persona.direccion.numero = int.Parse(collection.Get("direccion.numero"));
                persona.direccion.piso = int.Parse(collection.Get("direccion.piso"));
                persona.direccion.departamento = collection.Get("direccion.departamento");
                persona.direccion.localidad = collection.Get("direccion.localidad");
                persona.direccion.codigoPostal = int.Parse(collection.Get("direccion.codigoPostal"));
                persona.direccion.provincia = collection.Get("direccion.provincia");
                if (direccionPersonaComponent.Create(persona)is null)
                {
                    return RedirectToAction("ErrorPage", new { id = persona.persona.Id });
                   
                }
                else
                {
                    return RedirectToAction("Index", new { id = persona.persona.Id });
                }
                
            }
            catch (Exception e)
            {
                return View();
            }
        }
        [AuthorizerUser(_roles: "Administrador")]
        //
        // GET: /DireccionPersona/Edit/5
        public ActionResult Edit(int id,int dni)
        {
            DireccionPersona persona = new DireccionPersona();
            DireccionComponent direccion = new DireccionComponent();
            PersonaComponent personaComponent = new PersonaComponent();
            persona.direccion = direccion.ReadBy(id);
            persona.persona = personaComponent.ReadBy(dni);


            return View(persona);
        }
        [AuthorizerUser(_roles: "Administrador")]
        //
        // POST: /DireccionPersona/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                Direccion persona = new Direccion();
                DireccionComponent direccionPersonaComponent = new DireccionComponent();
                int a = int.Parse(collection.Get("persona.id"));
                persona.Id =int.Parse( collection.Get("direccion.id"));
                persona.direccion = collection.Get("direccion.direccion");
                persona.numero = int.Parse(collection.Get("direccion.numero"));
                persona.piso = int.Parse(collection.Get("direccion.piso"));
                persona.departamento = collection.Get("direccion.departamento");
                persona.localidad = collection.Get("direccion.localidad");
                persona.codigoPostal = int.Parse(collection.Get("direccion.codigoPostal"));
                persona.provincia = collection.Get("direccion.provincia");
                if (direccionPersonaComponent.Update(persona))
                {
                    
                    return RedirectToAction("Index", new { id = a });
                }
                else
                {
                    return RedirectToAction("ErrorPage", new { id = a });
                }
            }
            catch
            {
                return View();
            }
        }
        [AuthorizerUser(_roles: "Administrador")]
        //
        // GET: /DireccionPersona/Delete/5
        public ActionResult Delete(int id,int dni)
        {

            DireccionPersona persona = new DireccionPersona();
            PersonaComponent personaComponent = new PersonaComponent();
            persona.persona = personaComponent.ReadBy(dni);
            DireccionComponent direccion = new DireccionComponent();
            persona.direccion = direccion.ReadBy(id);
            return View(persona);
        }
        [AuthorizerUser(_roles: "Administrador")]
        //
        // POST: /DireccionPersona/Delete/5
        [HttpPost]
        public ActionResult Delete( FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                DireccionPersona direccion = new DireccionPersona();
                DireccionPersonaComponent direccionPersona = new DireccionPersonaComponent();

                direccion.persona.Id = int.Parse(collection.Get("persona.Id"));

                direccion.direccion.Id = int.Parse(collection.Get("direccion.Id"));
                direccionPersona.Delete(direccion.persona.Id, direccion.direccion.Id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SudamericanGreen/Views/DireccionPersona/Create.cshtml
@model Entities.DireccionPersona

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<link href="~/Content/modern-business.css" rel="stylesheet" />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="d-flex flex-column" style="max-width:60%">
    <div class="container-fluid">
        <div class="card shadow mb-4">
            <div class=" card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Crear una direccion para <i>  @Model.persona.usuarios.Nombre  @Model.persona.usuarios.Apellido </i> </h6>



            </div>
            <div class="card-body">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <h5 class="text-justify">
                    @Html.LabelFor(model => model.direccion, new { @class = "control-label col-md-2" })
                </h5>

                @Html.EditorFor(model => model.direccion.direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.direccion.direccion, "", new { @class = "text-danger" })
                <br />

                <br />
                <h5 class="text-justify">
                    @Html.LabelFor(model => model.direccion.numero, new { @class = "control-label col-md-2" })
                </h5>

                @Html.EditorFor(model => model.direccion.numero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.direccion.numero, "", new { @class = "text-danger" })
                <br />
                <br />
                <h5 class="text-justify">
                    @Html.LabelFor(model => model.direccion.piso, new { @class = "control-label col-md-2" })
                </h5>

                @Html.EditorFor(model => model.direccion.piso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.direccion.piso, "", new { @class = "text-danger" })

                <br />
                <br />
                <h5 class="text-justify">
                    @Html.LabelFor(model => model.direccion.departamento, new { @class = "control-label col-md-2" })
                </h5>

                @Html.EditorFor(model => model.direccion.departamento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.direccion.departamento, "", new { @class = "text-danger" })
                <br />
                <br />

                <h5 class="text-justify">
                    @Html.LabelFor(model => model.direccion.localidad, new { @class = "control-label col-md-2" })
                </h5>

                @Html.EditorFor(model => model.direccion.localidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.direccion.localidad, "", new { @class = "text-danger" })
                <br />
                <br />

                <h5 class="text-justify">
                    @Html.LabelFor(model => model.direccion.codigoPostal, new { @class = "control-label col-md-2" })
                </h5>

                @Html.EditorFor(model => model.direccion.codigoPostal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.direccion.codigoPostal, "", new { @class = "text-danger" })
                <br />
                <br />

                <h5 class="text-justify">
                    @Html.LabelFor(model => model.direccion.provincia, new { @class = "control-label col-md-2" })
                </h5>

                @Html.EditorFor(model => model.direccion.provincia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.direccion.provincia, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.persona.Id)




            </div>
            <input type="button" class="btn btn-outline-primary " value="Volver" onclick="location.href='@Url.Action("Index", "DireccionPersona",new { id=Model.persona.Id})'" />

            <br />

            <input type="submit" value="Crear" class="btn btn-outline-info" />
        </div>

    </div>
</div>
}

SudamericanGreen/Views/DireccionPersona/Delete.cshtml
@model Entities.DireccionPersona

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}




<link href="~/Content/modern-business.css" rel="stylesheet" />

<div>
    <h3>¿Esta seguro de eliminar la direccion de  <i> @Model.persona.usuarios.Nombre  @Model.persona.usuarios.Apellido</i>?</h3>
    <hr />


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.direccion.Id)@Html.HiddenFor(model => model.persona.Id)


        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" style="margin-left:1%" class="btn btn-outline-info" />
            <br />
            <input type="button" class="btn btn-outline-primary " style="float:left;margin-left:1%;margin-top:3%" value="Volver" onclick="location.href='@Url.Action("Index", "Permiso")'" />
        </div>
    }
</div>

SudamericanGreen/Views/DireccionPersona/Edit.cshtml
@model Entities.DireccionPersona

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<link href="~/Content/modern-business.css" rel="stylesheet" />


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="d-flex flex-column" style="max-width:60%">
        <div class="container-fluid">
            <div class="card shadow mb-4">
                <div class=" card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Actualizar una direccion para <i>  @Model.persona.usuarios.Nombre  @Model.persona.usuarios.Apellido </i> </h6>



                </div>
                <div class="card-body">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <h5 class="text-justify">
                        @Html.LabelFor(model => model.direccion, new { @class = "control-label col-md-2" })
                    </h5>

                    @Html.EditorFor(model => model.direccion.direccion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.direccion.direccion, "", new { @class = "text-danger" })



                    <h5 class="text-justify">
                        @Html.LabelFor(model => model.direccion.numero, new { @class = "control-label col-md-2" })
                    </h5>

                    @Html.EditorFor(model => model.direccion.numero, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.direccion.numero, "", new { @class = "text-danger" })



                    <h5 class="text-justify">
                        @Html.LabelFor(model => model.direccion.piso, new { @class = "control-label col-md-2" })
                    </h5>

                    @Html.EditorFor(model => model.direccion.piso, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.direccion.piso, "", new { @class = "text-danger" })



                    <h5 class="text-justify">
                        @Html.LabelFor(model => model.direccion.departamento, new { @class = "control-label col-md-2" })
                    </h5>

                    @Html.EditorFor(model => model.direccion.departamento, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.direccion.departamento, "", new { @class = "text-danger" })



                    <h5 class="text-justify">
                        @Html.LabelFor(model => model.direccion.localidad, new { @class = "control-label col-md-2" })
                    </h5>

                    @Html.EditorFor(model => model.direccion.localidad, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.direccion.localidad, "", new { @class = "text-danger" })



                    <h5 class="text-justify">
                        @Html.LabelFor(model => model.direccion.codigoPostal, new { @class = "control-label col-md-2" })
                    </h5>

                    @Html.EditorFor(model => model.direccion.codigoPostal, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.direccion.codigoPostal, "", new { @class = "text-danger" })



                    <h5 class="text-justify">
                        @Html.LabelFor(model => model.direccion.provincia, new { @class = "control-label col-md-2" })
                    </h5>

                    @Html.EditorFor(model => model.direccion.provincia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.direccion.provincia, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.persona.Id)
                    @Html.HiddenFor(model => model.direccion.Id)
                    <br />
                    <input type="button" class="btn btn-outline-primary " style="margin-left:40%;max-width:40%" value="Volver" onclick="location.href='@Url.Action("Index", "DireccionPersona",new { id=Model.persona.Id})'" />

                    <br />
                    <br />
                    <input type="submit" style="margin-left:39%;max-width:40%" value="Actualizar" class="btn btn-outline-info" />

                </div>
            </div>

        </div>
    </div>
}

SudamericanGreen/Views/DireccionPersona/ErroPage.cshtml
@model Entities.DireccionPersona

@{
    ViewBag.Title = "ErroPage";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}



<link href="~/Content/modern-business.css" rel="stylesheet" />



<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">



        <!-- Begin Page Content -->
        <div class="container-fluid">

            <!-- 404 Error Text -->
            <div class="text-center">
                <div class="error mx-auto" data-text="Error">Error</div>
                <p class="lead text-gray-800 mb-5">No se puede agregrar o modificar el la direccion.Ya existe
<p class="text-gray-500 mb-0">Por favor colocar otro nombre</p>
                <a href="@Url.Action("Index", "DireccionPersona",new { id=Model.persona.Id})">← volver al inicio</a>
            </div>

        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->

SudamericanGreen/Views/DireccionPersona/Index.cshtml
@model Entities.DireccionPersona

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<link href="~/Content/modern-business.css" rel="stylesheet" />
<div id="content-wrapper" class="d-flex flex-column">
    <!-- Main Content -->
    <div id="content">

        <!-- Begin Page Content -->
        <div class="container-fluid">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                   
                        <h6 class="m-0 font-weight-bold text-primary">Lista de Direccion de <i> @Model.persona.usuarios.Nombre  @Model.persona.usuarios.Apellido</i></h6>
                   

                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                            <div class="col-sm-12">
                                <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                    <thead>

                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 103px;">@Html.DisplayNameFor(model => model.direccion.direccion)</th>
                                       
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 162px;">@Html.DisplayNameFor(model => model.direccion.numero)</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 162px;">@Html.DisplayNameFor(model => model.direccion.piso)</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 162px;">@Html.DisplayNameFor(model => model.direccion.departamento)</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 162px;">@Html.DisplayNameFor(model => model.direccion.localidad)</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 162px;">@Html.DisplayNameFor(model => model.direccion.provincia)</th>

                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 162px;">Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.direccionPersona)
                                        {
                                            <tr role="row" class="odd">
                                              
                                                <td class="sorting_1">
                                                    @Html.DisplayFor(modelItem => item.direccion.direccion)
                                                </td>
                                                <td class="sorting_1">
                                                    @Html.DisplayFor(modelItem => item.direccion.numero)
                                                </td>
                                                <td class="sorting_1">
                                                    @Html.DisplayFor(modelItem => item.direccion.piso)
                                                </td>
                                                <td class="sorting_1">
                                                    @Html.DisplayFor(modelItem => item.direccion.departamento)
                                                </td>
                                                <td class="sorting_1">
                                                    @Html.DisplayFor(modelItem => item.direccion.localidad)
                                                </td>
                                                <td class="sorting_1">
                                                    @Html.DisplayFor(modelItem => item.direccion.provincia)
                                                </td>
                                                <td>

                                                    @Html.ActionLink("Eliminar", "Delete", new { id = item.direccion.Id, dni=item.persona.Id })|
                                                    @Html.ActionLink("Editar", "Edit", new { id = item.direccion.Id, dni = item.persona.Id })
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>
                  
                        <input type="button" class="btn btn-outline-primary " style="float:right" value="Crear" onclick="location.href='@Url.Action("create", "DireccionPersona",new { id=Model.persona.Id})'" />
                    
                </div>
            </div>
        </div>
    </div>
</div>